sonar.projectKey=ImKrav_HomaraBackend2
sonar.organization=homara
sonar.host.url=https://sonarcloud.io

# Directorios de análisis
sonar.sources=src
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts

# Exclusiones
sonar.exclusions=src/generated/**
sonar.coverage.exclusions=src/generated/**,tests/**,src/domain/repositories/**,src/infrastructure/entrypoints/**

# Reporte de cobertura LCOV (compatible con JavaScript y TypeScript)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Codificación
sonar.sourceEncoding=UTF-8
